### ISSUE TITLE
In editor python file, pyslide should be pyside

### ISSUE THREAD

**Issue by Merlin04** [ahtn/keyplus#46]
Also, when I try to install pyside, it gives errors:
```
    -- Could NOT find LibXslt (missing: LIBXSLT_LIBRARIES LIBXSLT_INCLUDE_DIR) (Required is at least version "1.1.19")
    Qt QTGUI library not found.
    Qt QTXML library not found.
    Qt QTCORE library not found.
    CMake Error at ApiExtractor/CMakeLists.txt:82 (qt4_add_resources):
      Unknown CMake command "qt4_add_resources".

```

**Comment by ahtn** [comment]
I tried to search for "pyslide" but couldn't find any references to it in the code, could you be more specific on which file you are referencing.

Also, what OS are you using. If you are on Windows, there's a executable that bundles everything into one binary [on the releases page](https://github.com/ahtn/keyplus/releases).

I'll try get instructions and an executable for Linux soon too, but I need to setup a clean environment to test on.

**Comment by Merlin04** [comment]
Never mind, I've misread. I'm using Ubuntu 17.10.
