### ISSUE TITLE
Audio keycodes not working

### ISSUE THREAD

**Issue by BillyBuerger** [ahtn/keyplus#69]
I've tried volume_up, volu and audio_vol_up and the same for volume down and mute and nothing changes with the system audio.  I've changed the keycodes to normal characters and those work so the switches themselves are working and it's not a hardware/matrix issue.

Keyplus Rev3
Firmware 0.3.1

**Comment by ahtn** [comment]
Actually fixed already, but forgot to add it to the master branch ed58ae830f9653.  I'll try merge it in tomorrow.

**Comment by ahtn** [comment]
Should be fixed in [this release](https://github.com/ahtn/keyplus/releases/tag/v0.3.2).
